In [1]:
from ezfalcon.simulation import Sim
import numpy as np

In [2]:
sim = Sim()
sim.add_particles('a', np.random.normal(size=(30, 3)) * 0.5, np.zeros((30, 3)), np.ones(30) * 1e4)
#sim.turn_self_gravity_off()
sim.run(t_end=2, dt=1, dt_out=2, eps=0.1)
#np.testing.assert_array_equal(sim.self_gravity_acc(-1), 0)
#assert np.all(np.isclose(sim.compute_self_gravity(0.1, 0.6, 0), 0, rtol=1e-10))

100%|██████████| 2/2 [00:00<00:00, 3876.44it/s]


In [3]:
sim.compute_self_gravity(0.01, 0.01, 0)

array([[ 7.45488762e-07, -5.54797843e-08,  4.38904024e-08],
       [ 1.70095177e-07,  4.27401432e-07, -5.49722131e-07],
       [ 8.62539991e-07,  3.03642622e-07, -1.56190687e-08],
       [-6.30017283e-09,  1.87382824e-07, -8.22748291e-07],
       [-8.22280924e-07, -5.07025334e-07,  8.49715946e-07],
       [ 6.67902270e-07, -3.90084836e-07, -4.35929593e-07],
       [ 5.14976080e-07,  3.98944366e-07, -3.86894953e-07],
       [ 5.01716045e-07,  1.20613933e-07,  5.47851528e-07],
       [ 8.76145009e-07,  1.50714584e-07,  6.26382871e-07],
       [ 1.80487376e-07, -7.07768265e-07,  8.85293105e-07],
       [-3.74838294e-07, -8.95889301e-08, -1.09243285e-06],
       [-5.38577126e-07,  2.00173176e-07,  4.30905317e-07],
       [-1.20828759e-06, -3.78160564e-07, -7.45807029e-07],
       [ 6.77154333e-07, -7.33546642e-07,  4.11909582e-07],
       [-1.86378685e-07,  8.79265997e-07,  1.32205764e-06],
       [ 3.32936565e-07,  3.09512638e-09, -1.19969528e-07],
       [ 1.70010779e-07,  2.37267204e-06

In [4]:

np.isclose(sim.compute_self_gravity(0.01, 0.1, 0), 0, atol=1e-6)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True, False],
       [ True,  True,  True],
       [False,  True,  True],
       [ True,  True,  True],
       [ True,  True, False],
       [ True,  True,  True],
       [ True, False, False],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True, False, False],
       [False, False,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True, False],
       [ True,  True,  True],
       [False,  True,  True],
       [ True, False,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [48]:
from ezfalcon.util import G_INTERNAL
BINARY_TEST_POS, BINARY_TEST_VELS, BINARY_TEST_MASS = (
    np.array([[0, -1, 0], [0, 1, 0]]),
    np.array([[1, 0, 0], [0, 0, 2]]),
    np.array([1, 2])
)
np.array(-G_INTERNAL * BINARY_TEST_MASS[0] * (BINARY_TEST_POS[1] - BINARY_TEST_POS[0]) / (
    np.linalg.norm(BINARY_TEST_POS[1] - BINARY_TEST_POS[0]))**3)

array([-0.00000000e+00, -1.12462554e-12, -0.00000000e+00])

In [38]:
-G_INTERNAL * BINARY_TEST_MASS[0] * BINARY_TEST_MASS[1] * (BINARY_TEST_POS[1] - BINARY_TEST_POS[0])

array([-0.0000000e+00, -8.9970043e-12, -0.0000000e+00])

In [39]:
(np.linalg.norm(BINARY_TEST_POS[1] - BINARY_TEST_POS[0]))**3

np.float64(8.0)

In [40]:
np.array(-G_INTERNAL * BINARY_TEST_MASS[0] * BINARY_TEST_MASS[1] * (BINARY_TEST_POS[1] - BINARY_TEST_POS[0])/ (
    np.linalg.norm(BINARY_TEST_POS[1] - BINARY_TEST_POS[0]))**3)

array([-0.00000000e+00, -1.12462554e-12, -0.00000000e+00])

In [41]:
BINARY_TEST_SIM = Sim()
BINARY_TEST_SIM.add_particles('comp1', 
                            pos=BINARY_TEST_POS, 
                            vel=BINARY_TEST_VELS, 
                            mass=BINARY_TEST_MASS)
BINARY_TEST_SIM.run(t_end=1, dt=0.5, dt_out=0.5, eps=0.01, theta=0.001)

BINARY_TEST_KE = 0.5 * BINARY_TEST_MASS * np.linalg.norm(BINARY_TEST_VELS, axis=-1)**2

BINARY_TEST_SELF_PE = np.array([-G_INTERNAL * BINARY_TEST_MASS[0] * BINARY_TEST_MASS[1] / (
    np.linalg.norm(BINARY_TEST_POS[1] - BINARY_TEST_POS[0])), 0])

100%|██████████| 2/2 [00:00<00:00, 6288.31it/s]


In [42]:
BINARY_TEST_SIM.self_ax(t=0)

array([0., 0.])

In [43]:
BINARY_TEST_SIM.self_gravity_acc(t=0)

array([[ 0.00000000e+00,  1.12462546e-12,  0.00000000e+00],
       [ 0.00000000e+00, -1.12462546e-12,  0.00000000e+00]])

In [44]:
BINARY_TEST_SIM.compute_self_gravity(t=0, eps=0.0001, theta=0.001)

array([[ 0.00000000e+00,  1.12462557e-12,  0.00000000e+00],
       [ 0.00000000e+00, -1.12462557e-12,  0.00000000e+00]])

In [55]:
KEPLER_SIM = Sim()
from galpy.potential import KeplerPotential
kepler_pot = KeplerPotential(amp=1.0)
KEPLER_SIM.add_external_pot('kepler', kepler_pot)
KEPLER_SIM.add_particles('a', pos=np.array([[0.1, 0, 0]]), vel=np.array([[0, 0.1, 0]]), mass=np.array([0.01]))
KEPLER_SIM.run(t_end=2, dt=1, dt_out=2, eps=0.1)


acc = KEPLER_SIM.external_acc(0)
expected_acc = np.array([-G_INTERNAL * 1.0 * 0.01 * 0.1 / (0.1**3), 0, 0])
# assert np.isclose(acc, expected_acc, rtol=1e-10)

100%|██████████| 2/2 [00:00<00:00, 1284.43it/s]


In [54]:
acc

array([[1.54718818e-04, 7.68242705e-05, 0.00000000e+00]])

In [52]:
expected_acc

array([-4.49850215e-12,  0.00000000e+00,  0.00000000e+00])